// these are here so you can simulate chat
export const seedGames = [
  "World of Goo 2",
  "Hades II",
  "Hollow Knight: Silksong",
  "Starfield",
  "The Legend of Zelda: Tears of the Kingdom",
  "Elden Ring",
  "Baldur's Gate 3",
  "Sea of Stars",
  "Dave the Diver",
  "Cyberpunk 2077",
  "The Witcher 3",
  "Fortnite",
  "League of Legends",
  "Minecraft",
  "Apex Legends",
  "Valorant",
  "Overwatch 2",
  "Super Mario Bros Wonder",
  "Resident Evil 4 Remake",
  "Final Fantasy XVI",
  "Persona 5 Royal",
  "Monster Hunter Rise",
  "Among Us",
  "Stardew Valley",
  "Dead Cells",
  "Cult of the Lamb",
  "Risk of Rain 2",
  "Slay the Spire",
  "Ghost of Tsushima",
  "God of War Ragnarok",
  "Spider-Man 2",
  "Lies of P",
  "Armored Core VI",
  "F-Zero 99",
  "Sonic Superstars",
  "Metroid Dread",
  "Cuphead",
  "Inside",
  "Celeste",
  "It Takes Two",

  // Expanded games
  "Sifu",
  "Returnal",
  "Hi-Fi Rush",
  "Tunic",
  "The Pathless",
  "The Talos Principle II",
  "Little Nightmares II",
  "Ori and the Will of the Wisps",
  "Alan Wake II",
  "Control",
  "Death Stranding",
  "Disco Elysium",
  "Fire Emblem: Three Houses",
  "Triangle Strategy",
  "Octopath Traveler II",
  "Xenoblade Chronicles 3",
  "Pikmin 4",
  "Bayonetta 3",
  "Dredge",
  "Unpacking",
  "Stray",
  "Spiritfarer",
  "Rogue Legacy 2",
  "Vampire Survivors",
  "The Binding of Isaac: Repentance",
  "Terraria",
  "Noita",
  "Deep Rock Galactic",
  "Hunt: Showdown",
  "Phasmophobia",
  "Escape from Tarkov",
  "Darkest Dungeon II",
  "BattleBit Remastered",
  "Palworld",
  "Enshrouded",
  "The Finals",
  "Manor Lords",
  "Helldivers 2"
];

export const usernames = [
  "gamer123",
  "speedrunner",
  "zeldaFan99",
  "proplayer",
  "noobmaster",
  "gamequeen",
  "pixelhero",
  "controllerking",
  "streamgod",
  "chatwarrior",
  "frostbyte",
  "pixelwizard",
  "ninjachad",
  "bossSlayer",
  "darkmage",
  "silentarrow",
  "rocketron",
  "hypernova",
  "midnightowl",
  "blitzkrieg",
  "toxicbunny",
  "grindmaster",
  "luckyshot",
  "soulcrusher",
  "ghostgamer",
  "couchpotato",
  "tryhardtimmy",
  "1hpclutch",
  "headshotqueen",
  "lagbeast",
  "aimbotwannabe",
  "criticalfail",
  "ultimatenoob",
  "afklegend",
  "fastfingers",
  "highpinghero",
  "carryqueen",
  "lobbyloser",
  "victoryroyal",
  "pressstart",
];
const subMsg = {
  msg: "!vote Sea of Stars",
  userstate: {
    "badge-info": {
      subscriber: "51",
    },
    badges: {
      subscriber: "48",
      turbo: "1",
    },
    "client-nonce": "7e6dbf75973513ceed819d7359e1d2ac",
    color: null,
    "display-name": "mithestral",
    emotes: null,
    "first-msg": false,
    flags: null,
    id: "c6817551-3c59-43dd-aaec-27d9ca9998a9",
    mod: false,
    "returning-chatter": false,
    "room-id": "23161357",
    subscriber: true,
    "tmi-sent-ts": "1745693925592",
    turbo: true,
    "user-id": "25627129",
    "user-type": null,
    "emotes-raw": null,
    "badge-info-raw": "subscriber/51",
    "badges-raw": "subscriber/48,turbo/1",
    username: "mithestral",
    "message-type": "chat",
  },
};

const rewardMsg = {
  msg: "!vote World of Goo 2",
  userstate: {
    color: "#5EFF00",
    "custom-reward-id": "b6dd266d-6855-4da4-88cb-8773a9ed76ad",
    "display-name": "Battottv",
    emotes: null,
    "first-msg": false,
    id: "82680deb-37c1-4500-8d49-4416f75bf8a5",
    subscriber: false,
    turbo: true,
    "user-id": "22322782",
    username: "battottv",
    "message-type": "chat",
  },
};

export const demoMsg = {
  sub: subMsg,
  reward: rewardMsg,
};
